### ISSUE TITLE
SUMMARY: Satisfactory

### ISSUE THREAD

**Issue by jzhu01** [heemet/prj-rev-bwfs-dasmoto#5]
Great job on this project! I really liked your usage of IDs, and the organization of your html file - it was very easy to read. In terms of improvement, I recommend giving the spans a class.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the stellar work! ^_^

**Comment by heemet** [comment]
Thanks so much for the feedback! And thanks also for the helpful link on laying out a grid - I've been wondering about that ;)
